### ISSUE TITLE
offset between the image and the overlay

### ISSUE THREAD

**Issue by domhardt** [yaqwsx/Pinion#11]
There is an offset between the image and the overlay in Safari 14.1.1 on MacOS 10.15.7
<img width="1440" alt="Bildschirmfoto 2021-06-06 um 14 33 40" src="https://user-images.githubusercontent.com/1955290/120924541-82843180-c6d4-11eb-8546-4db3ea7d66dd.png">

**Comment by dzarda** [comment]
Also the case on main w/ Windows/Firefox 90 *when maximized*:
![obrazek](https://user-images.githubusercontent.com/3955056/121089698-d3387f00-c7e7-11eb-851d-3e3a4aac2a81.png)

**Comment by OndroNR** [comment]
Chrome 91, macOS 11.4, retina display

![image](https://user-images.githubusercontent.com/978340/121152467-86839100-c845-11eb-9942-79fe36a73052.png)

**Comment by yaqwsx** [comment]
This was probably broken by 92f28cd3c8137e4b274be2adc954b06ba8d48d2e, should be fixed in 7e802695fd610745050dc3acfefc9ea5b74c76da. Please let me know if it works. I don't have Mac available to test it.
