### ISSUE TITLE
Bottom sliver not clickable

### ISSUE THREAD

**Issue by dzarda** [yaqwsx/Pinion#12]
There's an unhappy DIV at the bottom of the page that apparently eats click and hover events, therefore not allowing interaction with the items hidden behind it:
![obrazek](https://user-images.githubusercontent.com/3955056/121090773-57d7cd00-c7e9-11eb-9f4b-8f4972a115c9.png)

**Comment by yaqwsx** [comment]
Fixed in 18576ae507452bc3d93250e128db2775b1a097c0
