### ISSUE TITLE
TH component not clickable from other side

### ISSUE THREAD

**Issue by dzarda** [yaqwsx/Pinion#13]
I feel like we should allow having a throughhole component clickable (highlight visible) from both sides.

Suggested logic for driving the clickableness from both sides: 

```
isSMD = are all pads SMD
clickableFromBothSides = !isSMD
```

Current behaviour with a Stepdown component:

Yes (highlighted):
![obrazek](https://user-images.githubusercontent.com/3955056/121093661-9ec7c180-c7ed-11eb-81b6-aaca443db91c.png)

No (after switching sides):
![obrazek](https://user-images.githubusercontent.com/3955056/121093704-b30bbe80-c7ed-11eb-91d2-e966649f023e.png)

**Comment by dzarda** [comment]
Might consider driving via YAML, not sure if wanted.

**Comment by dzarda** [comment]
Consider a different highlight when viewed from bottom?

**Comment by yaqwsx** [comment]
Implemented in d725536
