### ISSUE TITLE
Overlapped component not clickable

### ISSUE THREAD

**Issue by dzarda** [yaqwsx/Pinion#14]
- Want to highlight STM32 (green)
- Hover (white) onto STM32
- Large region of overlapping OLED footprint is highlighted (yellow)

![obrazek](https://user-images.githubusercontent.com/3955056/127232492-a124f4f4-321d-472e-9b05-ccb74df221db.png)

**Comment by dzarda** [comment]
Possible solution - prefer region according to center point proximity.

**Comment by yaqwsx** [comment]
Solved in f6109b62350b0464cf8d9d9a0e45dbbce146d0b8
