### ISSUE TITLE
Highlight on SMD possible from both sides

### ISSUE THREAD

**Issue by dzarda** [yaqwsx/Pinion#7]
SMD component with `highlight: true` is clickable from the other side.

Good LED:
![obrazek](https://user-images.githubusercontent.com/3955056/120087234-81587080-c0e6-11eb-9057-7f6cea9eae0d.png)

Bad LED:
![obrazek](https://user-images.githubusercontent.com/3955056/120087257-acdb5b00-c0e6-11eb-812c-f44d2ba1d240.png)

**Comment by dzarda** [comment]
I suppose the logic for `is component SMD` would boil down to `are all pads SMD`

**Comment by yaqwsx** [comment]
Implemented in 38f7df9
