### ISSUE TITLE
'Maximize' crops lower part

### ISSUE THREAD

**Issue by dzarda** [yaqwsx/Pinion#9]
Maximize enlarges the display but does not allow to view all of it (no scrollbar)

![obrazek](https://user-images.githubusercontent.com/3955056/120707273-6ad16100-c4ba-11eb-9b56-9f087713b006.png)

**Comment by yaqwsx** [comment]
Fuh, this one was harder - apparently, I don't understand the HTML box model. Implemented in 92f28cd3c8137e4b274be2adc954b06ba8d48d2e
